version: "3"
services:
  mongo:
    image: mongo:3.6.0
    container_name: mongo
    tmpfs: /data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"