# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protos.suppliers_pb2 as suppliers__pb2


class SupplierStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSuppliersByCodes = channel.unary_unary(
                '/Supplier/GetSuppliersByCodes',
                request_serializer=suppliers__pb2.SuppliersByCodesRequest.SerializeToString,
                response_deserializer=suppliers__pb2.SuppliersByCodesResponse.FromString,
                )


class SupplierServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSuppliersByCodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SupplierServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSuppliersByCodes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSuppliersByCodes,
                    request_deserializer=suppliers__pb2.SuppliersByCodesRequest.FromString,
                    response_serializer=suppliers__pb2.SuppliersByCodesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Supplier', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Supplier(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSuppliersByCodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Supplier/GetSuppliersByCodes',
            suppliers__pb2.SuppliersByCodesRequest.SerializeToString,
            suppliers__pb2.SuppliersByCodesResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
